---
- name: ensure packages are installed for Deb-based os 
  apt: name={{item}} state=present
  with_items:
  - postgresql
  - libpq-dev
  - python-psycopg2
  when: ansible_pkg_mgr == "apt"

- name: ensure packages are installed for RHEL
  yum: name={{item}} state=present
  with_items:
  - postgresql
  - libpq-dev
  - python-psycopg2
  when: ansible_pkg_mgr == "yum"
