---
- name: ensure packages are installed for Deb-based os 
  apt: name={{item}} state=present
  with_items:
    - uwsgi 
  when: ansible_pkg_mgr == "apt"

- name: ensure packages are installed for RHEL
  yum: name={{item}} state=present
  with_items:
    - uwsgi 
  when: ansible_pkg_mgr == "yum"
