---
- name: Install supervisor for RHEL
  yum: name=supervisor state=present
  when: ansible_pkg_mgr == "yum"

- name: Install supervisor for Debian
  apt: name=supervisor state=present
  when: ansible_pkg_mgr == "apt"
