- name: ensure apt cache is up to date
  apt: update_cache=yes
  when: ansible_pkg_mgr == "apt"

- name: ensure yum cache is up to date
  yum: update_cache=yes
  when: ansible_pkg_mgr == "yum"

- name: install RHEL packages
  yum: name={{item}} state=present
  with_items:
  - git
  - python-pip
  - python-dev 
  - libjpeg-dev 
  - zlib1g-dev 
  - libpng12-dev
  - sudo
  when: ansible_pkg_mgr == "yum"

- name: install Debian packages
  apt: name={{item}} state=present
  with_items:
  - git
  - python-pip
  - python-dev 
  - libjpeg-dev 
  - zlib1g-dev 
  - libpng12-dev
  - sudo
  when: ansible_pkg_mgr == "apt"
